# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(140, 10, 541, 521))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.ImageViewer = QtWidgets.QGraphicsView(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageViewer.sizePolicy().hasHeightForWidth())
        self.ImageViewer.setSizePolicy(sizePolicy)
        self.ImageViewer.setObjectName("ImageViewer")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ImageViewer)
        self.graphicsView = QtWidgets.QGraphicsView(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.graphicsView)
        self.generateButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.generateButton.setObjectName("generateButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.generateButton)
        self.predictButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.predictButton.setObjectName("predictButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.predictButton)
        self.trainButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.trainButton.setObjectName("trainButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.trainButton)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label)
        self.b1 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.b1.setObjectName("b1")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.b1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generateButton.setText(_translate("MainWindow", "Generate data"))
        self.predictButton.setText(_translate("MainWindow", "Predict"))
        self.trainButton.setText(_translate("MainWindow", "Train"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.b1.setText(_translate("MainWindow", "Press for fun "))
